#!/bin/bash

# simple system information script

wms=(berry awesomewm easywm slimwm SlimWM tinywm bspwm sway hyprland dwl i3 fusionwm dwm openbox twobwm pekwm)

# define colors for color-echo
red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
rst="\e[0m"

color-echo() {  # print with colors
   printf "$red$1$cyn%10s : $rst$3\n" "$2"
}

print-kernel() {
   color-echo "$1" "KERNEL" "$(uname -smr)"
}

print-uptime() {
   up=$(</proc/uptime)
   up=${up//.*}                # string before first . is seconds
   days=$((${up}/86400))       # seconds divided by 86400 is days
   hours=$((${up}/3600%24))    # seconds divided by 3600 mod 24 is hours
   mins=$((${up}/60%60))       # seconds divided by 60 mod 60 is mins
   
   color-echo "$1" "UPTIME" "$(echo $days'd '$hours'h '$mins'm')"
}

print-shell() {
   color-echo "$1" "SHELL" $SHELL
}

print-cpu() {
   cpu=$(grep -m1 -i ''  /proc/cpuinfo)
   short_cpu=$(echo "$cpu" | sed 's/.*: \([A-Za-z0-9 ]*\) @.*/\1/')  # Remove Intel(R) Core(TM) part
   color-echo "$1" "CPU" "$short_cpu"
}

print-disk() {
   # field 2 on line 2 is total, field 3 on line 2 is used
   disk=$(df -h / | awk 'NR==2 {total=$2; used=$3; print used" / "total}')
   color-echo "$1" "DISK" "$disk"
}

print-mem() {
   # field 2 on line 2 is total, field 3 on line 2 is used (in new format)
   if [[ $(free -m) =~ "buffers" ]]; then # using old format
      mem=$(free -m | awk 'NR==2 {total=$2} NR==3 {used=$3; print used"M / "total"M"}')
   else # using new format
      mem=$(free -m | awk 'NR==2 {total=$2} NR==2 {used=$3; print used"M / "total"M"}')
   fi

   color-echo "$1" "MEMORY" "$mem"
}

print-wm() {
   for wm in ${wms[@]}; do
      pid=$(pgrep -x -u $USER $wm) # if found, this wmname has running process
      if [[ "$pid" ]]; then
         color-echo "$1" "WM" $wm
         break
      fi
   done
}

print-distro() {
   [[ -e /etc/os-release ]] && source /etc/os-release
   if [[ -n "$PRETTY_NAME" ]]; then
      color-echo "$1" "DISTRO" "$PRETTY_NAME"
   else
      color-echo "$1" "OS" "not found"
   fi
}

print-packages() {
   package_count=$(find /usr/bin -type f | wc -l)
   color-echo "$1" "PACKAGES" "$package_count (usr/bin)"
}

print-resolution() {
   res=$(xwininfo -root | grep 'geometry' | awk '{print $2}' | cut -d+ -f1)
   color-echo "$1" "RESOLUTION" $res
}

print-init() {
   init=$(readlink /proc/1/exe | awk -F'/' '{print $NF}')
   
   case "$init" in
      "systemd")
         color-echo "$1" "Init System" "systemd"
         ;;
      "runit")
         color-echo "$1" "Init System" "runit"
         ;;
      "init")
         # check if init is sysvinit or openrc
         if [[ -f "/etc/init.d" ]]; then
            if [[ -f "/etc/init.d/system" ]]; then
               color-echo "$1" "Init System" "sysvinit"
            else
               color-echo "$1" "Init System" "OpenRC"
            fi
         else
            color-echo "$1" "Init System" "Unknown"
         fi
         ;;
      *)
         color-echo "$1" "Init System" "$init"
         ;;
   esac
}

current_time=$(date +"%H:%M - %d/%m/%Y")

print-tarballs() {
   tarballs=$(find /home/$USER/sources -type f -name "*.tar.*" | wc -l)  # changed to user's home directory
   color-echo "$1" "Tarballs" "$tarballs"
}

print-patches() {
   patches=$(find /home/$USER/sources -type f -name "*.patch" | wc -l)  # changed to user's home directory
   color-echo "$1" "Patches" "$patches"
}

print-c-library() {
   if [[ -f /lib/libc.so.6 ]]; then
      libc=$(readlink /lib/libc.so.6)
      if [[ $libc == *"musl"* ]]; then
         color-echo "$1" "C Library" "musl"
      else
         color-echo "$1" "C Library" "glibc"
      fi
   else
      color-echo "$1" "C Library" "Not found"
   fi
}

print-modules() {
   modules=$(lsmod | wc -l)
   color-echo "$1" "MODULES" "$modules"
}

print-cpu-info() {
   cpu_info=$(lscpu | grep -E 'CPU(s)|MHz')
   color-echo "$1" "CPU Info" "$cpu_info"
}

print-top-processes() {
   top_processes=$(ps aux --sort=-%mem | head -n 10 | awk '{print $1, $2, $3, $11}' | column -t)
   color-echo "$1" "Top Processes (by memory)" "$top_processes"
}

print-cpu-freq() {
   cpu_freq=$(cat /proc/cpuinfo | grep 'cpu MHz' | awk '{print $4}' | head -n 1)
   color-echo "$1" "CPU FREQ" "$cpu_freq MHz"
}

print-disk-io() {
   disk_io=$(iostat -d | awk 'NR==4 {print "Read: "$3"KB/s, Write: "$4"KB/s"}')
   color-echo "$1" "DISK I/O" "$disk_io"
}

print-network-stats() {
   if command -v ifstat > /dev/null; then
      network_stats=$(ifstat -i eth0 1 1 | tail -n 1)
      color-echo "$1" "Network Stats (eth0)" "$network_stats"
   else
      color-echo "$1" "Network Stats (eth0)" "ifstat command not found"
   fi
}

print-open-files() {
   open_files=$(lsof | wc -l)
   color-echo "$1" "Open Files" "$open_files"
}

print-cpu-temp() {
   cpu_temp=$(sensors | grep 'Core 0' | awk '{print $3}')  # Adjust to your sensor output
   color-echo "$1" "CPU TEMP" "$cpu_temp"
}

print-uptime-detail() {
   uptime_info=$(uptime -p)
   load_avg=$(uptime | awk '{print $8,$9,$10}')
   color-echo "$1" "UPTIME" "$uptime_info, Load Avg: $load_avg"
}

print-panel() {
   panels=(polybar xfce4-panel slimpanel mate-panel gnome-panel lxpanel tint2 plank cairo-dock)
   for panel in ${panels[@]}; do
      pid=$(pgrep -x -u $USER $panel) # if found, this panel has a running process
      if [[ "$pid" ]]; then
         color-echo "$1" "PANEL" "$panel"
         return  # Exit after finding the first running panel
      fi
   done
   # If no panel is detected, do nothing (no output)
}

color-echo "$1" "DATE" "$current_time"

print-distro
print-kernel
print-mem
print-cpu-freq
print-cpu-temp
print-resolution
print-uptime
print-packages
print-disk
print-shell
print-modules
print-wm
print-tarballs
print-patches
print-panel
